// LOCALHOST 
### get all
GET http://localhost:8080/contacts 
### get Bruce Wayne
GET http://localhost:8080/contacts/62a56e6fdffc7b057c056976
### get Clark Kent
GET http://localhost:8080/contacts/62a56e8edffc7b057c05ac12
### get Hal Jordan
GET http://localhost:8080/contacts/62a56eaddffc7b057c05eecc

### Insert new contact
POST http://localhost:8080/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "TestFirstName1",
    "lastName": "TestLastName1",
    "email": "TestEmail1@gmail.com",
    "favoriteColor": "TestColor1",
    "birthday": "01/01/1111"
}

### Delete contact
DELETE http://localhost:8080/contacts/62aac2b1994138b80053b195

### Update Bruce Wayne's contact to Terry McGinnis
PUT http://localhost:8080/contacts/62a56e6fdffc7b057c056976 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Terry",
    "lastName": "McGinnis",
    "email": "batman@beyond.net",
    "favoriteColor": "Blue",
    "birthday": "08/18/2023"
}

### Update Bruce Wayne's contact back to Bruce Wayne
PUT http://localhost:8080/contacts/62a56e6fdffc7b057c056976 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Bruce",
    "lastName": "Wayne",
    "email": "notBatman@wayne.industries",
    "favoriteColor": "Black",
    "birthday": "04/17/1969"
}




// Production https://jmg-03-personal.herokuapp.com/ 
### get all
GET https://jmg-03-personal.herokuapp.com/contacts
### get Bruce Wayne
GET https://jmg-03-personal.herokuapp.com/contacts/62a56e6fdffc7b057c056976
### get Clark Kent
GET https://jmg-03-personal.herokuapp.com/contacts/62a56e8edffc7b057c05ac12
### get Hal Jordan
GET https://jmg-03-personal.herokuapp.com/contacts/62a56eaddffc7b057c05eecc
###

### Insert new contact
POST https://jmg-03-personal.herokuapp.com/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "TestFirstName1",
    "lastName": "TestLastName1",
    "email": "TestEmail1@gmail.com",
    "favoriteColor": "TestColor1",
    "birthday": "01/01/1111"
}

### Delete contact
DELETE https://jmg-03-personal.herokuapp.com/contacts/62ab42cb916e36355b3f89cc

### Update Bruce Wayne's contact to Terry McGinnis
PUT https://jmg-03-personal.herokuapp.com/contacts/62a56e6fdffc7b057c056976 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Terry",
    "lastName": "McGinnis",
    "email": "batman@beyond.net",
    "favoriteColor": "Blue",
    "birthday": "08/18/2023"
}

### Update Bruce Wayne's contact back to Bruce Wayne.
PUT https://jmg-03-personal.herokuapp.com/contacts/62a56e6fdffc7b057c056976 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Bruce",
    "lastName": "Wayne",
    "email": "notBatman@wayne.industries",
    "favoriteColor": "Black",
    "birthday": "04/17/1969"
}